<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class DosenSisterSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Buat Admin Dulu (Paling Atas)
    \App\Models\User::updateOrCreate(
        ['email' => 'admin@gmail.com'],
        [
            'name' => 'Administrator',
            'password' => bcrypt('admin'),
            'role' => 'admin',
        ]
    );
        $dataDosen = [
            ['name' => 'Damil', 'penempatan' => 'S1 - Teknik Informatika'],
            ['name' => 'AAN KARDIANA', 'penempatan' => 'S1 - Teknik Informatika'],
            ['name' => 'AAN ROYHAN', 'penempatan' => 'S1 - Kedokteran'],
            ['name' => 'ADE NURSANTI', 'penempatan' => 'S1 - Psikologi'],
            ['name' => 'AFRIZAL TW', 'penempatan' => 'S1 - Kedokteran'],
            ['name' => 'AGUNG FRIJANTO', 'penempatan' => 'Profesi - Profesi Dokter'],
            ['name' => 'AGUS ARDINANSYAH', 'penempatan' => 'S1 - Kedokteran Gigi'],
            ['name' => 'AGUS RIFAI', 'penempatan' => 'S1 - Perpustakaan dan Sains Informasi'],
            ['name' => 'AGUS WIDY PURNOMO', 'penempatan' => 'S1 - Akuntansi'],
            ['name' => 'AHMAD RONAL', 'penempatan' => 'Profesi - Profesi Dokter Gigi'],
            ['name' => 'AHMAD RUSDAN HANDOYO UTOMO', 'penempatan' => 'S3 - Sains Biomedis'],
            ['name' => 'AHMAD SABIQ', 'penempatan' => 'S1 - Teknik Informatika'],
            ['name' => 'ALABANYO BREBAHAMA', 'penempatan' => 'S1 - Psikologi'],
            ['name' => 'AL ICHSAN', 'penempatan' => 'S1 - Kedokteran'],
            ['name' => 'ALI MA\'SUM', 'penempatan' => 'S1 - Manajemen'],
            ['name' => 'ALISA NOVIANTY PRATIWI', 'penempatan' => 'S1 - Kedokteran Gigi'],
            ['name' => 'ALYTA SHABRINA ZUSRYN', 'penempatan' => 'S1 - Manajemen'],
            ['name' => 'AMBAR HARDJANTI', 'penempatan' => 'S1 - Kedokteran'],
            ['name' => 'AMELIA KRESNA', 'penempatan' => 'Profesi - Profesi Dokter'],
            ['name' => 'AMINAH AHMAD ALAYDRUS', 'penempatan' => 'Profesi - Profesi Dokter'],
            ['name' => 'AMIN MANSUR', 'penempatan' => 'S1 - Manajemen'],
            ['name' => 'AMIRAH YUSNIDAR', 'penempatan' => 'S1 - Kedokteran'],
            ['name' => 'AMIR MAHMUD', 'penempatan' => 'S1 - Ilmu Hukum'],
            ['name' => 'ANANTA HAGABEAN', 'penempatan' => 'S1 - Manajemen'],
            ['name' => 'ANDI ADYTHA M I R', 'penempatan' => 'S1 - Kedokteran Gigi'],
            ['name' => 'ANDI ALFIAN', 'penempatan' => 'Profesi - Profesi Dokter'],
            ['name' => 'ANDI ERLINA', 'penempatan' => 'Profesi - Profesi Dokter'],
            ['name' => 'ANDIKA NURAGA BUDIMAN', 'penempatan' => 'S1 - Manajemen'],
            ['name' => 'ANDREAS FEBRIAN', 'penempatan' => 'S1 - Teknik Informatika'],
            ['name' => 'ANDRI GUNAWAN', 'penempatan' => 'S1 - Akuntansi'],
            ['name' => 'ANGGRAENI IRIANI', 'penempatan' => 'S1 - Kedokteran'],
            ['name' =>'ANGGRI MURTIA','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'ANIS BYARWATI','penempatan'=>'S2 - Manajemen'],
            ['name'=>'ANITA ROSA DELIMA','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'ANY SETIANINGRUM','penempatan'=>'S2 - Manajemen'],
            ['name'=>'ARIEL NIAN GANI','penempatan'=>'S1 - Manajemen'],
            ['name'=>'ARIFIANTO','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'ARIO ADI PRAKOSO','penempatan'=>'S1 - Perpustakaan dan Sains Informasi'],
            ['name'=>'ARROYAN WARDHANA','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'ARSYAD','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'ARYENTI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'ASTRI AVIANTI','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'ASWIN JANUARSYAF','penempatan'=>'S1 - Psikologi'],
            ['name'=>'ATIEK ANDRIAWATI','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'AUDIAWATI','penempatan'=>'Profesi - Profesi Dokter Gigi'],
            ['name'=>'AULIFFI ERMIAN CHALLEN','penempatan'=>'S1 - Akuntansi'],
            ['name'=>'AYA YAHYA MAULANA','penempatan'=>'S1 - Perpustakaan dan Sains Informasi'],
            ['name'=>'BAMBANG POERWANTORO','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'BAMBANG S TRENGGONO','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'BEVITA','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'BIMO RINTOKO','penempatan'=>'Profesi - Profesi Dokter Gigi'],
            ['name'=>'CESARIO BUDI PRAYITNO','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'CHAERITA MAULANI','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'CHANDRADEWI KUSRISTANTI','penempatan'=>'S1 - Psikologi'],
            ['name'=>'CHANDRA PRASETYO UTOMO','penempatan'=>'S1 - Teknik Informatika'],
            ['name'=>'CHANDRA YUSUF','penempatan'=>'S2 - Kenotariatan'],
            ['name'=>'CHRISNI OKTAVIA JUSUP','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'CITRA FITRI AGUSTINA','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'DANANG DWIJO KANGKO','penempatan'=>'S1 - Perpustakaan dan Sains Informasi'],
            ['name'=>'DANIAL RASYID','penempatan'=>'S2 - Administrasi Rumah Sakit'],
            ['name'=>'DEDE ARSISTA','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'DEVA BACHTIAR','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'DEWI KUMALASARI','penempatan'=>'S1 - Psikologi'],
            ['name'=>'DEWI NURUL MUSTAQIMAH','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'DHARMA SATYA APRIANTO','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'DHINASTY ARMENIA WIRAKUSUMAH','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'DIAN EKA PUTRI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'DIAN MARDHIYAH','penempatan'=>'Sp-1 - Kedokteran Keluarga Layanan Primer'],
            ['name'=>'DIAN WIDIYANTI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'DICKY BUDIMAN','penempatan'=>'S2 - Administrasi Rumah Sakit'],
            ['name'=>'DILFA JUNIAR','penempatan'=>'S1 - Psikologi'],
            ['name'=>'DINIWATI MUCHTAR','penempatan'=>'S3 - Sains Biomedis'],
            ['name'=>'DINI WIDIANTI','penempatan'=>'Sp-1 - Kedokteran Keluarga Layanan Primer'],
            ['name'=>'DJUNED PRASONTO','penempatan'=>'Profesi - Profesi Dokter Gigi'],
            ['name'=>'DODIK PRANATA WIJAYA','penempatan'=>'S1 - Ilmu Hukum'],
            ['name'=>'DR. DHARMA PERMANA,APT','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'DR EKO PURWANTO','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'DR ERI DIAN MAHARSI M KES','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'DRG MOCHAMAD ATMAJI WINDRIANTO MSI','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'DRG NUGROHO AHMAD RIYADI','penempatan'=>'Profesi - Profesi Dokter Gigi'],
            ['name'=>'DR RIKA FERLIANTI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'DR. TJANDRA YOGA ADITAMA','penempatan'=>'S3 - Sains Biomedis'],
            ['name'=>'DR. WENING SARI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'EDI PRASETYO','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'EDWARD SYAM','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'EFENDY ZAIN','penempatan'=>'S1 - Manajemen'],
            ['name'=>'ELAN SUHERLAN','penempatan'=>'S1 - Teknik Informatika'],
            ['name'=>'ELITA DONANTI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'ELMANIZAR','penempatan'=>'S1 - Akuntansi'],
            ['name'=>'ELSYE SOUVRIYANTI','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'ELY ALAWIYAH JUFRI','penempatan'=>'S1 - Ilmu Hukum'],
            ['name'=>'ELY NURHAYATI','penempatan'=>'S1 - Manajemen'],
            ['name'=>'ENDAH PURNAMASARI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'ENDANG FOURIANALISTYAWATI','penempatan'=>'S1 - Psikologi'],
            ['name'=>'ENDANG PURWANINGSIH','penempatan'=>'S3 - Sains Biomedis'],
            ['name'=>'ENDANG ENDANG FOURIANALISTYAWATI','penempatan'=>'S1 - Ilmu Hukum'],
            ['name'=>'ENDY MUHAMMAD ASTIWARA','penempatan'=>'S2 - Administrasi Rumah Sakit'],
            ['name'=>'ENTIN NURHAYATI','penempatan'=>'S1 - Psikologi'],
            ['name'=>'ERLINA WIJAYANTI','penempatan'=>'Sp-1 - Kedokteran Keluarga Layanan Primer'],
            ['name'=>'ETTY WIDAYANTI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'EVA SRI DIANA','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'EVIE RACHMAWATI NUR ARIYANTI','penempatan'=>'S1 - Ilmu Hukum'],
            ['name'=>'FAIZAL DRISSA HASIBUAN','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'FARAH PRIMADANI KAUROW','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'FATHIMAH AZZAHRA ATTAMIMI','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'FATHUL JANNAH','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'FATIMAH ELIANA','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'FERRYAL BASBETH','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'FIRMAN ARIFANDI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'FITA MAULINA','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'FITRI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'FITRI ARLINKASARI','penempatan'=>'S1 - Psikologi'],
            ['name'=>'FRENGKI HARDIAN','penempatan'=>'S2 - Kenotariatan'],
            ['name'=>'GOTOT SUMANTRI','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'HADIATI FITRI','penempatan'=>'S2 - Manajemen'],
            ['name'=>'HADI FIRMANSYAH SIDIQ','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'HARLIANSYAH','penempatan'=>'S2 - Sains Biomedis'],
            ['name'=>'HARRY BUDIANTORO','penempatan'=>'S1 - Akuntansi'],
            ['name'=>'HASTUTI RAHMI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'HELWIAH UMNIYATI','penempatan'=>'Profesi - Profesi Dokter Gigi'],
            ['name'=>'HENDRA WICAKSONO SUKOWATI','penempatan'=>'S1 - Perpustakaan dan Sains Informasi'],
            ['name'=>'HERIKA HAYURANI','penempatan'=>'S1 - Teknik Informatika'],
            ['name'=>'HERI SAMTANI','penempatan'=>'S1 - Perpustakaan dan Sains Informasi'],
            ['name'=>'HESTI WITASARI JOS ERRY','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'HESTY JUNI TAMBUATI SUBING','penempatan'=>'S1 - Akuntansi'],
            ['name'=>'HILMA SUYANA','penempatan'=>'S1 - Manajemen'],
            ['name'=>'HIMMI MARSIATI','penempatan'=>'S3 - Sains Biomedis'],
            ['name'=>'HULMANSYAH','penempatan'=>'S2 - Administrasi Rumah Sakit'],
            ['name'=>'IDA RATNA NURHIDAYATI','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'IKE IRMAWARI PURBO A','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'IMELDA SARI','penempatan'=>'S1 - Akuntansi'],
            ['name'=>'INDA DWI LESTANTRI','penempatan'=>'S1 - Teknik Informatika'],
            ['name'=>'INDAH KURNIANINGSIH','penempatan'=>'S1 - Perpustakaan dan Sains Informasi'],
            ['name'=>'INDAH NADILLA','penempatan'=>'S1 - Ilmu Hukum'],
            ['name'=>'INDRA KUSUMA','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'INTAN FARIDA YASMIN','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'INTAN KEUMALA DEWI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'INTAN TRI ANNISA','penempatan'=>'S1 - Manajemen'],
            ['name'=>'IRFAN ISLAMI','penempatan'=>'S1 - Ilmu Hukum'],
            ['name'=>'IRFAN SYARIF','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'IRWANDI M ZEN LC','penempatan'=>'S1 - Teknik Informatika'],
            ['name'=>'IRWAN SANTOSA','penempatan'=>'S2 - Kenotariatan'],
            ['name'=>'ISA MULTAZAM NOOR','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'ISKANDAR MUDA','penempatan'=>'S2 - Kenotariatan'],
            ['name'=>'JOHAN SATRIA PUTRA','penempatan'=>'S1 - Psikologi'],
            ['name'=>'JULIANI KUSUMAPUTRA','penempatan'=>'Profesi - Profesi Dokter Gigi'],
            ['name'=>'JUNIARTI','penempatan'=>'S2 - Sains Biomedis'],
            ['name'=>'KAMAL ANAS','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'KARIMULLOH','penempatan'=>'S1 - Psikologi'],
            ['name'=>'KARINA DEWI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'KENCONO VIYATI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'KHOLIS ERNAWATI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'KUSMARDI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'LADIADHAN HUKAMA','penempatan'=>'S1 - Manajemen'],
            ['name'=>'LENDA KOMALA','penempatan'=>'S1 - Akuntansi'],
            ['name'=>'LEONY HESTORIA','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'LIA GARDENIA PARTAKUSUMA','penempatan'=>'S2 - Administrasi Rumah Sakit'],
            ['name'=>'LIANA ZULFA','penempatan'=>'Profesi - Profesi Dokter Gigi'],
            ['name'=>'LIKO MARYUDHIYANTO','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'LILIAN BATUBARA','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'LILY DEVIASTRI','penempatan'=>'S1 - Manajemen'],
            ['name'=>'LINDA ARMELIA','penempatan'=>'Sp-1 - Kedokteran Keluarga Layanan Primer'],
            ['name'=>'LINDA WENI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'LISA PRIHASTARI','penempatan'=>'Profesi - Profesi Dokter Gigi'],
            ['name'=>'LIZA EVITA','penempatan'=>'S1 - Ilmu Hukum'],
            ['name'=>'LUKMAN HAMDANI','penempatan'=>'S1 - Manajemen'],
            ['name'=>'LUSIANA','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'LUSY LIANY','penempatan'=>'S2 - Kenotariatan'],
            ['name'=>'MARISA RILIANI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'MASAGUS ASAARI','penempatan'=>'S1 - Akuntansi'],
            ['name'=>'MAYA GENISA SSI MT','penempatan'=>'S2 - Sains Biomedis'],
            ['name'=>'MAYA TRISISWATI','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'MEDIAN WILESTARI','penempatan'=>'S1 - Akuntansi'],
            ['name'=>'MELOK RORO KINANTHI','penempatan'=>'S1 - Psikologi'],
            ['name'=>'MIRANTI PUSPARINI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'MIRFAT','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'MIWA PATNANI','penempatan'=>'S1 - Psikologi'],
            ['name'=>'MOHAMAD KHARIS UMARDANI','penempatan'=>'S1 - Ilmu Hukum'],
            ['name'=>'MOHAMMAD RIZA SYAH','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'MOHAMMAD RYAN BAKRY','penempatan'=>'S2 - Kenotariatan'],
            ['name'=>'MUBARIK AHMAD','penempatan'=>'S1 - Teknik Informatika'],
            ['name'=>'MUHAMAD FATHURAHMAN','penempatan'=>'S1 - Teknik Informatika'],
            ['name'=>'MUHAMAD ZAKKI','penempatan'=>'Profesi - Profesi Dokter Gigi'],
            ['name'=>'MUHAMMAD AKHYAR ADNAN','penempatan'=>'S1 - Akuntansi'],
            ['name'=>'MUHAMMAD FAISAL','penempatan'=>'S1 - Akuntansi'],
            ['name'=>'MUHAMMAD GHAZALI','penempatan'=>'S1 - Akuntansi'],
            ['name'=>'MUHAMMAD IQBAL','penempatan'=>'S2 - Manajemen'],
            ['name'=>'MUHAMMAD NICKY NURFAJRI','penempatan'=>'Profesi - Profesi Dokter Gigi'],
            ['name'=>'MUHAMMAD ROFI\'I','penempatan'=>'S1 - Manajemen'],
            ['name'=>'MUH. FAZLURRAHMAN ANSHAR','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'MULYADI MUCHTIAR','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'MUSLIKH','penempatan'=>'S2 - Manajemen'],
            ['name'=>'NABILA PYRENINA THAMRIN','penempatan'=>'S2 - Sains Biomedis'],
            ['name'=>'NANDA OCTAVIA','penempatan'=>'S1 - Ilmu Hukum'],
            ['name'=>'NDARU ANDRI DAMAYANTI','penempatan'=>'S2 - Sains Biomedis'],
            ['name'=>'NELLY ULFAH ANISARIZA','penempatan'=>'S1 - Ilmu Hukum'],
            ['name'=>'NENDEN LILIS SETIASIH','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'NIDA NADYA HASAN','penempatan'=>'S1 - Akuntansi'],
            ['name'=>'NITA ISMAYATI','penempatan'=>'S1 - Perpustakaan dan Sains Informasi'],
            ['name'=>'NORMAN ZAINAL','penempatan'=>'S2 - Administrasi Rumah Sakit'],
            ['name'=>'NOVA EKA DIANA','penempatan'=>'S1 - Teknik Informatika'],
            ['name'=>'NOVIENDRI','penempatan'=>'S1 - Manajemen'],
            ['name'=>'NOVIKA GRASIASWATY','penempatan'=>'S1 - Psikologi'],
            ['name'=>'NOVI RAHAYU RESTUNINGRUM','penempatan'=>'S1 - Teknik Informatika'],
            ['name'=>'NOVI RESISTANTIE','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'NUGROHO BUDI SANTOSO','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'NUNUNG AINUR RAHMAH','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'NUR ASIAH','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'NURFIANTI','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'NUR HIDAYATI NOSI PRASTIYANI','penempatan'=>'Profesi - Profesi Dokter Gigi'],
            ['name'=>'NURI SADIDA','penempatan'=>'S1 - Psikologi'],
            ['name'=>'NUR ISNAENI EVRY KURNIAWATI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'NURMAYA','penempatan'=>'S1 - Teknik Informatika'],
            ['name'=>'NURUL FAJRI CHIKMAWATI','penempatan'=>'S1 - Ilmu Hukum'],
            ['name'=>'NURUL HUDA','penempatan'=>'S1 - Manajemen'],
            ['name'=>'OCTAVIANI INDRASARI R','penempatan'=>'S1 - Psikologi'],
            ['name'=>'OKKY MARITA ARDY','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'PANGISTI DWI ANANINGSIH','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'PARAMARESTHI WINDRIYANI','penempatan'=>'S1 - Teknik Informatika'],
            ['name'=>'PENNY RAHMAH FADHILAH','penempatan'=>'S1 - Manajemen'],
            ['name'=>'PERDANA WAHYU SANTOSA','penempatan'=>'S1 - Manajemen'],
            ['name'=>'PRASTIWI SETIANINGTYAS','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'PRATAMI ADITIANINGSARI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'QOMARIAH RS','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'RAFIYANDI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'RANDHY NUGROHO','penempatan'=>'S1 - Akuntansi'],
            ['name'=>'RATIH ARRUUM LISTIYANDINI','penempatan'=>'S1 - Psikologi'],
            ['name'=>'RESTU SYAMSUL HADI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'RETNO KUNTARI HERUYANTO','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'RIDARSON','penempatan'=>'S1 - Ilmu Hukum'],
            ['name'=>'RIDHAYANI','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'RIDWAN','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'RIFDA WULANSARI SPM KES','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'RIFQATUSSAADAH','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'RIKA BUR','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'RIKA NURAISYAH','penempatan'=>'Profesi - Profesi Dokter Gigi'],
            ['name'=>'RIKO HENDRAWAN','penempatan'=>'S1 - Manajemen'],
            ['name'=>'RINA RAHMATIKA','penempatan'=>'S1 - Psikologi'],
            ['name'=>'RINI HIDAYATI','penempatan'=>'S1 - Manajemen'],
            ['name'=>'RISELLIGIA CANINSTI','penempatan'=>'S1 - Psikologi'],
            ['name'=>'RITA KOMALASARI','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'RIZA APRIZAL','penempatan'=>'Sp-1 - Kedokteran Keluarga Layanan Primer'],
            ['name'=>'RIZKY RAMADHANA','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'ROMY ARWINDA','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'RONI HIDAYAT','penempatan'=>'S2 - Manajemen'],
            ['name'=>'ROSINI','penempatan'=>'S1 - Perpustakaan dan Sains Informasi'],
            ['name'=>'RUNI OKTAYANI','penempatan'=>'Profesi - Profesi Dokter Gigi'],
            ['name'=>'R W SUSILOWATI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'RYAN INDRA','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'SABRINA AZMI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'SAKURA MUHAMMAD TOLA','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'SARI ZAKIAH AKMAL','penempatan'=>'S1 - Psikologi'],
            ['name'=>'SELLY SEPTINA','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'SILPI HAMIDIYAH','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'SITI MARHAMAH','penempatan'=>'S1 - Manajemen'],
            ['name'=>'SITI MAULIDYA SARI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'SITI NUR RIANI','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'SOFA INAYATULLAH','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'SONNY PAMUJI LAKSONO','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'SONYA PRIYADHARSINI','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'SOVI ISMAWATI R','penempatan'=>'S1 - Akuntansi'],
            ['name'=>'SRI CHUSRI HARYANTI','penempatan'=>'S1 - Teknik Informatika'],
            ['name'=>'SRI HASTUTI ANDAYANI','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'SRI PUJI UTAMI','penempatan'=>'S1 - Teknik Informatika'],
            ['name'=>'SRI RAHAYU NINGSIH','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'SRI UTAMI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'SRI WAHYU HERLINAWATI','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'SRI WURYANTI','penempatan'=>'S2 - Administrasi Rumah Sakit'],
            ['name'=>'SUHAERI','penempatan'=>'S1 - Teknik Informatika'],
            ['name'=>'SUHIRMAN MADJID','penempatan'=>'S1 - Akuntansi'],
            ['name'=>'SULTANA MUHAMMAD HUSSEIN','penempatan'=>'S3 - Sains Biomedis'],
            ['name'=>'SUNU BAGASKARA','penempatan'=>'S1 - Psikologi'],
            ['name'=>'SURYO BANTOLO','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'SYAFRIZAL','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'SYAFRUDDIN A R LELOSUTAN','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'SYUKRINI BAHRI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'TASWEM TARIB','penempatan'=>'S1 - Ilmu Hukum'],
            ['name'=>'TEGUH YULIADI','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'TITIEK DJANNATUN','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'TITI SAHIDAH FITRIANA','penempatan'=>'S1 - Psikologi'],
            ['name'=>'TOTO HERIYANTO','penempatan'=>'S1 - Manajemen'],
            ['name'=>'TRESIA ELDA','penempatan'=>'S1 - Ilmu Hukum'],
            ['name'=>'TRI AGUS HARYONO','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'TUTY HERAWATY','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'UFO PRAMIGI','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'ULFAHIMAYATI','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'UMMI AZIZAH RACHMAWATI','penempatan'=>'S1 - Teknik Informatika'],
            ['name'=>'VERNI YULIATY ISMAIL','penempatan'=>'S1 - Manajemen'],
            ['name'=>'VIDHIA UMAMI','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'WAN NEDRA','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'WARDIYONO','penempatan'=>'S1 - Perpustakaan dan Sains Informasi'],
            ['name'=>'WASTUTI HIDAYATI SURIYAH','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'WINA HARTATY','penempatan'=>'S1 - Kedokteran Gigi'],
            ['name'=>'WITRI ABRIYA','penempatan'=>'Profesi - Profesi Dokter'],
            ['name'=>'YENNI ZULHAMIDAH','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'YURIKA SANDRA','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'YUSNITA','penempatan'=>'Sp-1 - Kedokteran Keluarga Layanan Primer'],
            ['name'=>'YUSUF SHOFIE','penempatan'=>'S1 - Ilmu Hukum'],
            ['name'=>'YUTRIZAL JACOUB','penempatan'=>'S1 - Manajemen'],
            ['name'=>'ZAINAL ZAWIR SIMON','penempatan'=>'S1 - Manajemen'],
            ['name'=>'ZAKIYAH','penempatan'=>'S1 - Kedokteran'],
            ['name'=>'ZULFA FEBRIANI','penempatan'=>'S1 - Psikologi'],
            ['name'=>'ZWASTA PRIBADI MAHARDHIKA','penempatan'=>'S1 - Kedokteran'],

        ];

       foreach ($dataDosen as $dosen) {
    User::create([
        'name'           => $dosen['name'],
        'email'          => strtolower(str_replace(' ', '.', $dosen['name'])) . '@gmail.com',
        'password'       => Hash::make('user'),
        'role'           => 'pengaju',
        'fakultas'       => $dosen['penempatan'], // Diubah dari fakultas_prodi ke fakultas
        'nidn'           => '00000000',           // Sekarang ini akan masuk karena kolom nidn ada
        'program_studi'  => null,
        'jabatan'        => 'Dosen',
    ]);
}
    }
}
